### ISSUE TITLE
Error starting PAPI eventset

### ISSUE THREAD

**Issue by kisaacs** [hdc-arizona/traveler-integrated#41]
<img width="915" alt="Screen Shot 2020-02-19 at 1 20 41 PM" src="https://user-images.githubusercontent.com/10036820/74872577-b5a58480-531a-11ea-8953-3314340ecf86.png">

This was taking the prior clean clone and going with the non-dev instructions instead. I then launched the notebook, did a Restart & Clear Output, and then ran all the cells.

**Comment by stevenrbrandt** [comment]
Is this using the image I created? We had PAPI working there.

**Comment by kisaacs** [comment]
Jetlag now updated. Old issue.
