### ISSUE TITLE
Ability to tag and filter jobs on the Uvicorn server

### ISSUE THREAD

**Issue by stevenrbrandt** [hdc-arizona/traveler-integrated#46]
I was thinking about setting up a tutorial server for use with Phylanx. I was thinking I'd need one server, each running on a unique port for each user. It occurred to me that it might be easier to have a single uvicorn server and give it the ability to filter jobs based on a tag. For this purpose, the only tag that I would care about would be "username," however, the mechanism might have other uses.

It would, of course, be "insecure" in that your job data would be viewable by anyone who filtered using your username tag. However, I think that sort of insecurity is acceptable.

It's possible you already have a feature like this and I just don't know about it. :)

**Comment by alex-r-bigelow** [comment]
We don't have a feature like this yet, but we discussed some tagging functionality in #28—thanks for the issue; it's really helpful for us to know that that feature is important.

In the mean time, maybe there's a way to substitute username for job ID as the dataset label from JetLag? It should still work, but list everyone's usernames would show up on the left for everyone to see...
