### ISSUE TITLE
Datasets uploaded via the API don't show up in the interface

### ISSUE THREAD

**Issue by alex-r-bigelow** [hdc-arizona/traveler-integrated#68]
As reported by @stevenrbrandt, this produces the correct output from the server, but doesn't list `FibFun2` as a dataset, even after a page refresh:

```python
from phylanx import Phylanx

def fib(n):
    if n < 2:
        return n
    else:
        return fib(n-1)+fib(n-2)

pfib = Phylanx(performance='x')(fib)

pfib(15)

argMap = {
    "csv": pfib.__perfdata__[0],
    "newick": pfib.__perfdata__[1],
    "dot": pfib.__perfdata__[2],
    "physl":pfib.get_physl_source(),
    "python": pfib.get_python_src(pfib.backend.wrapped_function)
}
import requests
base_url = "http://localhost:8000"
url = base_url + '/datasets/%s' % "FibFun2"
resp = requests.post(url, json=argMap)
```

**Comment by alex-r-bigelow** [comment]
@stevenrbrandt, I've finally fixed my broken Docker/WSL setup (took a full system reinstall... don't get me started...)

This is probably a stupid question, but I'm probably not using the right docker image. Attempting this in `stevenrbrandt/phylanx.devenv` keeps giving me the classic `ModuleNotFoundError: No module named 'phylax'` Should I be using a different one?

**Comment by stevenrbrandt** [comment]
You want the image "stevenrbrandt/phylanx.rel.test:working"

**Comment by alex-r-bigelow** [comment]
Hmm, now I'm getting `cannot import name 'Phylanx'`, but `import phylanx` works ... did something change in how we're supposed to import it?

**Comment by stevenrbrandt** [comment]
Try setting `export PYTHONUSERBASE=/usr/local/userbase`

**Comment by stevenrbrandt** [comment]
Did that work for you?

**Comment by alex-r-bigelow** [comment]
Yes... and no. Now having trouble getting the `requests` library installed inside the container... one sec

**Comment by stevenrbrandt** [comment]
If you'd used the docker image in JetLag, all this would be set up.

**Comment by alex-r-bigelow** [comment]
I tried that first, and got the same phylanx import issues

**Comment by stevenrbrandt** [comment]
I'm confused. You got that from the notebook?

**Comment by alex-r-bigelow** [comment]
Wait, the above code was supposed to be run in the notebook?!?  Oof, I need to bother you more about context next time

**Comment by stevenrbrandt** [comment]
Well, the notebook has the environment variables all setup and reqeusts installed. You don't need to use it.

**Comment by stevenrbrandt** [comment]
It would also have installed and started traveler, so all setup issues handled.

**Comment by alex-r-bigelow** [comment]
Hmm, trying to import phylanx directly in a JetLag notebook still has the import error (I figured before that it wasn't included, as JetLag is meant to be running phylanx remotely, so that's why I went down the route of your other docker images)

![image](https://user-images.githubusercontent.com/1215873/90045906-8ac23a80-dc84-11ea-9f69-ddd1352e7784.png)

**Comment by stevenrbrandt** [comment]
import os
print(os.environ['PYTHONUSERBASE'])

**Comment by alex-r-bigelow** [comment]
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-dd6db8644c21> in <module>
      1 import os
----> 2 print(os.environ['PYTHONUSERBASE'])

/usr/local/lib/python3.6/os.py in __getitem__(self, key)
    667         except KeyError:
    668             # raise KeyError with the original key value
--> 669             raise KeyError(key) from None
    670         return self.decodevalue(value)
    671 

KeyError: 'PYTHONUSERBASE'
```

**Comment by stevenrbrandt** [comment]
D'oh! I forgot to push the line where I added PYTHONUSERBASE to the notebook.

**Comment by stevenrbrandt** [comment]
Pushed. Sorry.

**Comment by stevenrbrandt** [comment]
All good?

**Comment by alex-r-bigelow** [comment]
Thanks for all the context (sorry about the delay; I accidentally did `docker system prune -a` instead of `docker volume prune` ...)

I was just able to reproduce, and it looks like everything is uploading correctly, but there **IS** a console error after all:

```
LinkedState.js:303 Uncaught TypeError: Cannot read property '1' of null
    at LinkedState.fetchGanttAggBins (LinkedState.js:303)
    at new LinkedState (LinkedState.js:35)
    at Controller.getLinkedState (controller.js:64)
    at HTMLLIElement.<anonymous> (SummaryView.js:65)
    at Ct.each (d3.min.js:2)
    at SummaryView.drawHelperViews (SummaryView.js:63)
    at SummaryView.draw (SummaryView.js:53)
    at uki.esm.js:179
```

@sayefsakin, I think this is the bug we anticipated earlier (#58): when datasets don't have any _otf2_ data (other use case: Kevin's regression testing, or when anyone tries to upload ), a lot of the new code that tries to calculate bins, etc, naturally fails. In the above example, `fetchGanttAggBins` (and related code) should probably never be called if there isn't any trace data.

**Comment by stevenrbrandt** [comment]
I thought I sent the console along? I said there was no *server* log error.

**Comment by alex-r-bigelow** [comment]
Hmm, I don't see that in the original email—sorry, I should have asked! Here I was doing all this, assuming this was a silent failure...

We'll get a patch up ASAP

**Comment by stevenrbrandt** [comment]
Oh, so this is about a lack of otf2 trace data?

**Comment by alex-r-bigelow** [comment]
Yes. It shouldn't ever be required, so definitely a bug on our end
