### ISSUE TITLE
Implement FunctionalBoxPlotView.js

### ISSUE THREAD

**Issue by alex-r-bigelow** [hdc-arizona/traveler-integrated#81]
This view was reset in the #79 UI overhaul, and needs to be re-implemented, specifically the `drawCanvas`, `drawAxes`, and `getChartShape` functions (may also require some server-side debugging / implementation of the `/datasets/ ... /metrics/ ... /summary` endpoint)

See comments in `static/views/FunctionalBoxPlotView.js` for details, including a link to the original implementation

**Comment by sayefsakin** [comment]
solved in PR https://github.com/hdc-arizona/traveler-integrated/pull/87
