### ISSUE TITLE
Support for latest python versions (3.9+)

### ISSUE THREAD

**Issue by sayefsakin** [hdc-arizona/traveler-integrated#84]
Runs into error with any later versions of python 3.9+
- Blist dependency

**Comment by albestro** [comment]
FIY

https://github.com/DanielStutzbach/blist/issues/90

**Comment by sayefsakin** [comment]
- [ ] Check compatibility with python 3.9 (address with this [PR ](https://github.com/hdc-arizona/traveler-integrated/pull/86))

- [ ] Check compatibility with python 3.10

**Comment by sayefsakin** [comment]
Due to the collection mapping [issue](https://github.com/googleapis/google-auth-library-python/pull/419), python 3.10 is not stable. Closing this issue for now.

**Comment by sayefsakin** [comment]
Closing this issue for now. Will address python 3.10 dependencies in a separate issue.
